flowchart TD
n0["."]
n1["amazonses.com"]
n0 --> n1
n2["GEO-classification:.ap .i.e. .ap"]
n1 --> n2
n3["directional:-northeast .i.e. -northeast"]
n2 --> n3
n4["digits@3:[1,3]for:3"]
n3 --> n4
n5["smtp"]
n4 --> n5
n6["UN-locode:US .i.e. -out"]
n5 --> n6
n7["a{ip2}-{ip3}"]
n6 --> n7
n8["c{ip2}-{ip3}"]
n6 --> n8
n9["h{ip2}-{ip3}"]
n6 --> n9
n10["directional:-southeast .i.e. -southeast"]
n2 --> n10
n11["digits@3:[1,3]for:3"]
n10 --> n11
n12["smtp"]
n11 --> n12
n13["UN-locode:US .i.e. -out"]
n12 --> n13
n14["e{ip2}-{ip3}"]
n13 --> n14
n15["a{ip2}-{ip3}"]
n13 --> n15
n16["c{ip2}-{ip3}"]
n13 --> n16
n17["gamma"]
n11 --> n17
n18["smtp"]
n17 --> n18
n19["UN-locode:US .i.e. -out"]
n18 --> n19
n20["c{ip2}-{ip3}"]
n19 --> n20
n21["directional:-south .i.e. -south"]
n2 --> n21
n22["digits@3:[1,1]for:1"]
n21 --> n22
n23["smtp"]
n22 --> n23
n24["UN-locode:US .i.e. -out"]
n23 --> n24
n25["c{ip2}-{ip3}"]
n24 --> n25
n26["h{ip2}-{ip3}"]
n24 --> n26
n27["GEO-classification:.eu .i.e. .eu"]
n1 --> n27
n28["{ip0}ntral"]
n27 --> n28
n29["digits@3:[1,1]for:1"]
n28 --> n29
n30["smtp"]
n29 --> n30
n31["UN-locode:US .i.e. -out"]
n30 --> n31
n32["h{ip2}-{ip3}"]
n31 --> n32
n33["directional:-south .i.e. -south"]
n27 --> n33
n34["digits@3:[1,1]for:1"]
n33 --> n34
n35["beta"]
n34 --> n35
n36["smtp"]
n35 --> n36
n37["UN-locode:US .i.e. -out"]
n36 --> n37
n38["c{ip2}-{ip3}"]
n37 --> n38
n39["smtp"]
n34 --> n39
n40["UN-locode:US .i.e. -out"]
n39 --> n40
n41["e{ip2}-{ip3}"]
n40 --> n41
n42["directional:-central .i.e. -central"]
n27 --> n42
n43["digits@3:[1,1]for:1"]
n42 --> n43
n44["smtp"]
n43 --> n44
n45["UN-locode:US .i.e. -out"]
n44 --> n45
n46["b{ip2}-{ip3}"]
n45 --> n46
n47["g{ip2}-{ip3}"]
n45 --> n47
n48["directional:-west .i.e. -west"]
n27 --> n48
n49["digits@3:[1,2]for:2"]
n48 --> n49
n50["smtp"]
n49 --> n50
n51["UN-locode:US .i.e. -out"]
n50 --> n51
n52["h{ip2}-{ip3}"]
n51 --> n52
n53["a{ip2}-{ip3}"]
n51 --> n53
n54["directional:-north .i.e. -north"]
n27 --> n54
n55["digits@3:[1,1]for:1"]
n54 --> n55
n56["smtp"]
n55 --> n56
n57["UN-locode:US .i.e. -out"]
n56 --> n57
n58["h{ip2}-{ip3}"]
n57 --> n58
n59["us"]
n1 --> n59
n60["UN-locode:US .i.e. -gov"]
n59 --> n60
n61["directional:-east .i.e. -east"]
n60 --> n61
n62["digits@4:[1,1]for:1"]
n61 --> n62
n63["smtp"]
n62 --> n63
n64["UN-locode:US .i.e. -out"]
n63 --> n64
n65["g{ip2}-{ip3}"]
n64 --> n65
n66["directional:-west .i.e. -west"]
n59 --> n66
n67["digits@3:[2,2]for:1"]
n66 --> n67
n68["smtp"]
n67 --> n68
n69["UN-locode:US .i.e. -out"]
n68 --> n69
n70["a{ip2}-{ip3}"]
n69 --> n70
n71["c{ip2}-{ip3}"]
n69 --> n71
n72["directional:-east .i.e. -east"]
n59 --> n72
n73["digits@3:[2,2]for:1"]
n72 --> n73
n74["smtp"]
n73 --> n74
n75["UN-locode:US .i.e. -out"]
n74 --> n75
n76["h{ip2}-{ip3}"]
n75 --> n76
n77["a{ip2}-{ip3}"]
n75 --> n77
n78["smtp"]
n1 --> n78
n79["UN-locode:US .i.e. -out"]
n78 --> n79
n80["h{ip2}-{ip3}"]
n79 --> n80
n81["a{ip2}-{ip3}"]
n79 --> n81
n82["c{ip2}-{ip3}"]
n79 --> n82
n83["GEO-classification:.ca .i.e. .ca"]
n1 --> n83
n84["directional:-central .i.e. -central"]
n83 --> n84
n85["digits@3:[1,1]for:1"]
n84 --> n85
n86["smtp"]
n85 --> n86
n87["UN-locode:US .i.e. -out"]
n86 --> n87
n88["g{ip2}-{ip3}"]
n87 --> n88
n89["a{ip2}-{ip3}"]
n87 --> n89
n90["GEO-classification:.sa .i.e. .sa"]
n1 --> n90
n91["directional:-east .i.e. -east"]
n90 --> n91
n92["digits@3:[1,1]for:1"]
n91 --> n92
n93["smtp"]
n92 --> n93
n94["UN-locode:US .i.e. -out"]
n93 --> n94
n95["a{ip2}-{ip3}"]
n94 --> n95
n96["h{ip2}-{ip3}"]
n94 --> n96